# Docker rules dependencies
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "4521794f0fba2e20f3bf15846ab5e01d5332e587e9ce81629c7f96c793bb7036",
    strip_prefix = "rules_docker-0.14.4",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.4/rules_docker-v0.14.4.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

# Example for using the deb_packages ruleset
http_archive(
    name = "rules_deb_packages",
    sha256 = "dc729b64a429e6670edefffa0fa917730552c01fd414bd161d9138b5ec04b9de",
    urls = ["https://github.com/petermylemans/rules_deb_packages/releases/download/v0.3.0/rules_deb_packages.tar.gz"],
)

load("@rules_deb_packages//:repositories.bzl", "deb_packages_dependencies")

deb_packages_dependencies()

load("@rules_deb_packages//:deb_packages.bzl", "deb_packages")

http_file(
    name = "buster_archive_key",
    sha256 = "9c854992fc6c423efe8622c3c326a66e73268995ecbe8f685129063206a18043",
    urls = ["https://ftp-master.debian.org/keys/archive-key-10.asc"],
)

http_file(
    name = "buster_security_archive_key",
    sha256 = "4cf886d6df0fc1c185ce9fb085d1cd8d678bc460e6267d80a833d7ea507a0fbd",
    urls = ["https://ftp-master.debian.org/keys/archive-key-10-security.asc"],
)

http_file(
    name = "ubuntu_key",
    sha256 = "50a57221cf2bedcaafb8a6a73f29ed71f153a30deae3ee7076dc2b9220e11cf0",
    urls = ["https://keyserver.ubuntu.com/pks/lookup?op=hget&search=12120bd49c566eaf49d31f267ec0b900"],
)

deb_packages(
    name = "debian_buster_amd64",
    arch = "amd64",
    packages = {
        "base-files": "pool/main/b/base-files/base-files_10.3+deb10u8_amd64.deb",
        "busybox": "pool/main/b/busybox/busybox_1.30.1-4_amd64.deb",
        "ca-certificates": "pool/main/c/ca-certificates/ca-certificates_20200601~deb10u2_all.deb",
        "libc6": "pool/main/g/glibc/libc6_2.28-10_amd64.deb",
        "libssl1.1": "pool/main/o/openssl/libssl1.1_1.1.1d-0+deb10u4_amd64.deb",
        "netbase": "pool/main/n/netbase/netbase_5.6_all.deb",
        "openssl": "pool/main/o/openssl/openssl_1.1.1d-0+deb10u4_amd64.deb",
        "tzdata": "pool/main/t/tzdata/tzdata_2021a-0+deb10u1_all.deb",
    },
    packages_sha256 = {
        "base-files": "eda9ec7196cae25adfa1cb91be0c9071b26904540fc90bab8529b2a93ece62b1",
        "busybox": "1e32ea742bddec4ed5a530ee2f423cdfc297c6280bfbb45c97bf12eecf5c3ec1",
        "ca-certificates": "a9e267a24088c793a9cf782455fd344db5fdced714f112a8857c5bfd07179387",
        "libc6": "6f703e27185f594f8633159d00180ea1df12d84f152261b6e88af75667195a79",
        "libssl1.1": "b02b468f0fad929b5d2b38ae05607c22c4f1ef70adc2688fb02b9d9514d6ac51",
        "netbase": "baf0872964df0ccb10e464b47d995acbba5a0d12a97afe2646d9a6bb97e8d79d",
        "openssl": "fa997ab8745f28ea3553ebc623872bb6809cc94898f6c72d81a757d9ee47dfe3",
        "tzdata": "00da63f221b9afa6bc766742807e398cf183565faba339649bafa3f93375fbcb",
    },
    sources = [
        "http://deb.debian.org/debian buster main",
        "http://deb.debian.org/debian buster-updates main",
        "http://deb.debian.org/debian-security buster/updates main",
    ],
    timestamp = "20210216T115751Z",
    urls = [
        "http://deb.debian.org/debian/$(package_path)",
        "http://deb.debian.org/debian-security/$(package_path)",
        "https://snapshot.debian.org/archive/debian/$(timestamp)/$(package_path)",  # Needed in case of supersed archive no more available on the mirrors
        "https://snapshot.debian.org/archive/debian-security/$(timestamp)/$(package_path)",  # Needed in case of supersed archive no more available on the mirrors
    ],
)

deb_packages(
    name = "ubuntu_bionic_amd64",
    arch = "amd64",
    packages = {
        "base-files": "pool/main/b/base-files/base-files_10.1ubuntu2.10_amd64.deb",
        "busybox": "pool/universe/b/busybox/busybox_1.27.2-2ubuntu3.3_amd64.deb",
        "ca-certificates": "pool/main/c/ca-certificates/ca-certificates_20210119~18.04.1_all.deb",
        "libc6": "pool/main/g/glibc/libc6_2.27-3ubuntu1.4_amd64.deb",
        "libssl1.1": "pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.7_amd64.deb",
        "netbase": "pool/main/n/netbase/netbase_5.4_all.deb",
        "openssl": "pool/main/o/openssl/openssl_1.1.1-1ubuntu2.1~18.04.7_amd64.deb",
        "tzdata": "pool/main/t/tzdata/tzdata_2021a-0ubuntu0.18.04_all.deb",
    },
    packages_sha256 = {
        "base-files": "9abf6982e61cabc44011247b8a39af39bf47cdb96cd12d898bf47b3ebe92a80e",
        "busybox": "a1b5ea4a7eb95fe3cadca78406af57c9bdb3b024d5060400fdff5344179ab1b0",
        "ca-certificates": "0eef06ee5c975fdf029b7b26d12701441cfd22c556927772b236f2bc5b39cc2e",
        "libc6": "46d39b8965f35457ce5db62662832c095fd7e01e72093da99ae025eb8e12bbe5",
        "libssl1.1": "6cba7ab11adfe998afb8a1c1b85bf1cb0449101cb4160402bac2507ccc72b632",
        "netbase": "cbda1c8035cd1fe0b1fb09b456892c0bb868657bfe02da82f0b16207d391145e",
        "openssl": "26eec06c925b5468e8c80cd0645c62e0ff613e60a074e5bf92dd9df127f67660",
        "tzdata": "7a28ea35faffb239a92f8f4ee204d64d5bec2ad308b04118d046334f44152e02",
    },
    sources = [
        "http://us.archive.ubuntu.com/ubuntu bionic main",
        "http://us.archive.ubuntu.com/ubuntu bionic-updates main",
        "http://us.archive.ubuntu.com/ubuntu bionic-backports main",
        "http://security.ubuntu.com/ubuntu bionic-security main universe",
    ],
    timestamp = "20210216T113505Z",
    urls = [
        "http://us.archive.ubuntu.com/ubuntu/$(package_path)",
        "http://security.ubuntu.com/ubuntu/$(package_path)",
        "https://launchpad.net/ubuntu/+archive/primary/+files/$(package_file)",  # Needed in case of supersed archive no more available on the mirrors
    ],
)
