name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install buildifier
        run: go get github.com/bazelbuild/buildtools/buildifier

      - name: Lint Starlark files
        run: buildifier -lint warn -mode check -r .

      - name: Lint Go files
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.32.2
