name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install buildifier
      run: go get github.com/bazelbuild/buildtools/buildifier

    - name: Check formatting Starlark files
      run: buildifier -lint warn -mode check -r .
